### PR TITLE
fix: transpile for browser

### PR DESCRIPTION
**Pull request by LewisYearsley**
See issue: https://github.com/wardpeet/gatsby-plugin-static-site/issues/32

We ran into this issue where the code in `gatsby-browser` is not transpiled and therefore modern features like arrow functions have been served to old browsers like IE11.

### CODE REVIEW

**Review by wardpeet — COMMENTED** [review]
Looks good, I'll merge it when all merges have been done

**Review by wardpeet — APPROVED** [review]

**Review by wardpeet — APPROVED** [review]
Thank you! :)

**Comment by LewisYearsley** [comment]
Cheers @wardpeet ! any idea when this change will be released to npm?

**Comment by wardpeet** [comment]
in a few minutes :)

**Comment by LewisYearsley** [comment]
🎊

**Comment by wardpeet** [comment]
Published in `@wardpeet/gatsby-plugin-static-site@0.2.3`

**Pull request merged**
