### PR TITLE
Include appropriate version of reach router

### LINKED ISSUE #5: Router override is not bundled by webpack
For some reason, when using the plugin, the override of `@reach/router` is not getting bundled by webpack.

This repo gatsby starter + plugin
https://github.com/xavivars/gatsbybug

and it's deployed here and doesn't work: 
http://gatsby-bug.s3-website-eu-west-1.amazonaws.com/notworking/page-2/

(you will see a redirect happening)

I can't understand why it works in here

http://gatsby-bug.s3-website-eu-west-1.amazonaws.com/gatsby/page-3/

(source code for this is coming from https://github.com/wardpeet/gatsby-demos/tree/static-asset-prefix )

### PR DESCRIPTION
**Pull request by xavivars**
Fixes https://github.com/wardpeet/gatsby-plugin-static-site/issues/5

### CODE REVIEW

**Comment by xavivars** [comment]
@wardpeet : Sorry to bug you... Any chances you look into this?

**Comment by wardpeet** [comment]
Hey sorry, i'll try to get to it somewhere this week, it has been a few busy weeks and I went on vacation.

**Comment by brianbento** [comment]
Any chance of getting this merged soon?

**Comment by xavivars** [comment]
Temporarily, while #9 and #11 get merged I've published a _fork_ of this plug-in with both PRs merged as https://www.npmjs.com/package/@xavivars/gatsby-plugin-static-site

**Comment by wardpeet** [comment]
Closing in favor of #16 

Thanks a lot @xavivars or all your work and creating the fork!

**Pull request closed without merging**
